/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

/**
 *
 * @author Ariana Egoavil Olive
 */
public class MenuOperador extends javax.swing.JFrame {
        
        private GestionarCandidato gestorCandidato = new GestionarCandidato();
        private GestionarPartidosPoliticos gestorPartido = new GestionarPartidosPoliticos();
        private GestionarMesasElectorales gestorMesas = new GestionarMesasElectorales();
        private GestionarMiembrosMesa gestorMiembros = new GestionarMiembrosMesa();
        private GestionarElecciones gestorElecciones = new GestionarElecciones();
        private GestionarActasElectorales gestorActas = new GestionarActasElectorales();
        



    /**
     * Creates new form MenuOperador
     */
    public MenuOperador(GestionarCandidato gestorCandidato, GestionarPartidosPoliticos gestorPartido,
        GestionarMesasElectorales gestorMesas, GestionarMiembrosMesa gestorMiembros,
        GestionarElecciones gestorElecciones, GestionarActasElectorales gestorActas ) {
         // esto es para que no se borre al regresar al MenuOperador
     
            this.gestorCandidato = gestorCandidato;
            this.gestorPartido = gestorPartido;
            this.gestorMesas= gestorMesas;
            this.gestorMiembros = gestorMiembros;
            this.gestorElecciones = gestorElecciones;
            this.gestorActas = gestorActas;
  
         initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCandidatos = new javax.swing.JButton();
        jButtonPartidoPolitico = new javax.swing.JButton();
        jButtonElecciones = new javax.swing.JButton();
        jButtonMesasElectorales = new javax.swing.JButton();
        jButtonMiembrosMesa = new javax.swing.JButton();
        jButtonActaElectoral = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU OPERADOR");

        jButtonCandidatos.setText("Candidatos");
        jButtonCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCandidatosActionPerformed(evt);
            }
        });

        jButtonPartidoPolitico.setText("Partidos Políticos");
        jButtonPartidoPolitico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPartidoPoliticoActionPerformed(evt);
            }
        });

        jButtonElecciones.setText("Elecciones");
        jButtonElecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEleccionesActionPerformed(evt);
            }
        });

        jButtonMesasElectorales.setText("Mesas Electorales");
        jButtonMesasElectorales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesasElectoralesActionPerformed(evt);
            }
        });

        jButtonMiembrosMesa.setText("Miembros de Mesa");
        jButtonMiembrosMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMiembrosMesaActionPerformed(evt);
            }
        });

        jButtonActaElectoral.setText("Actas Electorales");
        jButtonActaElectoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActaElectoralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPartidoPolitico)
                            .addComponent(jButtonCandidatos)
                            .addComponent(jButtonElecciones)
                            .addComponent(jButtonMesasElectorales)
                            .addComponent(jButtonMiembrosMesa)
                            .addComponent(jButtonActaElectoral))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonCandidatos)
                .addGap(18, 18, 18)
                .addComponent(jButtonPartidoPolitico)
                .addGap(18, 18, 18)
                .addComponent(jButtonElecciones)
                .addGap(18, 18, 18)
                .addComponent(jButtonMesasElectorales)
                .addGap(18, 18, 18)
                .addComponent(jButtonMiembrosMesa)
                .addGap(18, 18, 18)
                .addComponent(jButtonActaElectoral)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCandidatosActionPerformed
        // TODO add your handling code here:
        //Primer intento
        new VentanaGestionCandidatos(gestorCandidato).setVisible(true);
        this.dispose();      

        
    }//GEN-LAST:event_jButtonCandidatosActionPerformed

    private void jButtonMesasElectoralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesasElectoralesActionPerformed
        // TODO add your handling code here:
        
        new VentanaGestionMesasElectorales(gestorMesas).setVisible(true);
        this.dispose(); 
        
        
    }//GEN-LAST:event_jButtonMesasElectoralesActionPerformed

    private void jButtonPartidoPoliticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPartidoPoliticoActionPerformed
        // TODO add your handling code here:
        
        new VentanaGestionPartidos(gestorPartido).setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_jButtonPartidoPoliticoActionPerformed

    private void jButtonEleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEleccionesActionPerformed
        // TODO add your handling code here:
        new VentanaGestionElecciones(gestorElecciones).setVisible(true);     
        this.dispose(); 
        
    }//GEN-LAST:event_jButtonEleccionesActionPerformed

    private void jButtonMiembrosMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMiembrosMesaActionPerformed
        // TODO add your handling code here:
        new VentanaGestionMiembrosMesa(gestorMiembros).setVisible(true);
        this.dispose(); 
        
    }//GEN-LAST:event_jButtonMiembrosMesaActionPerformed

    private void jButtonActaElectoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActaElectoralActionPerformed
        // TODO add your handling code here:
       /* new VentanaGestionActasElectorales(
            gestorCandidato,
            gestorPartido,
            gestorMesas,
            gestorMiembros,
            gestorElecciones,
            gestorActas
        ).setVisible(true);
        this.dispose(); 
        */
        
        
    }//GEN-LAST:event_jButtonActaElectoralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            //cambio para que reciba todos los parametros que debería
            public void run() {
            GestionarCandidato gestorCandidatos = new GestionarCandidato();
            GestionarPartidosPoliticos gestorPartidos = new GestionarPartidosPoliticos();
            GestionarMesasElectorales gestorMesas = new GestionarMesasElectorales();
            GestionarMiembrosMesa gestorMiembros = new GestionarMiembrosMesa();
            GestionarElecciones gestorElecciones = new GestionarElecciones();
            GestionarActasElectorales gestorActas = new GestionarActasElectorales();
            
           new MenuOperador(gestorCandidatos, gestorPartidos, gestorMesas,
                                              gestorMiembros, gestorElecciones, 
                                              gestorActas).setVisible(true);            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActaElectoral;
    private javax.swing.JButton jButtonCandidatos;
    private javax.swing.JButton jButtonElecciones;
    private javax.swing.JButton jButtonMesasElectorales;
    private javax.swing.JButton jButtonMiembrosMesa;
    private javax.swing.JButton jButtonPartidoPolitico;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
